### ISSUE TITLE
Does OpenPerplex allows for search querying by URL parameters like Google do?

### ISSUE THREAD

**Issue by banditByte** [YassKhazzan/openperplex_backend_os#10]
I'm wondering if I can pass a search query in the following way:
"https://openperplex.com/search?query=search+query"?

**Comment by YassKhazzan** [comment]
no, this is not possible. you can use the openperplex API if you want to run search in your application or just self host this repo. [api.openperplex.com ](https://api.openperplex.com/apiKeys)

**Comment by banditByte** [comment]
> no, this is not possible. you can use the openperplex API if you want to run search in your application or just self host this repo. [api.openperplex.com ](https://api.openperplex.com/apiKeys)

Thanks for the quick response! However, it is a pity that there is no such option.

**Comment by YassKhazzan** [comment]
if there is such an option, i will be providing a search API for free!! you can self host the backend and run your queries.
