### ISSUE TITLE
Make the answer longer

### ISSUE THREAD

**Issue by tqdo** [YassKhazzan/openperplex_backend_os#11]
I am using the normal mode (not Pro) locally and the answer returned is pretty short compared to the one on the website. The response I get also does not feel as comprehensive as the one on the website. With api, I see there is a parameter `verbose_mode=True` to get a long response. Is there such parameter in the open source version as well?

**Comment by YassKhazzan** [comment]
Hello, you just have to change your prompt to make the answer longer.
