### ISSUE TITLE
What is the difference between the website and the open source version?

### ISSUE THREAD

**Issue by tqdo** [YassKhazzan/openperplex_backend_os#12]
I am truly impressed by the quality of openperplex website and excited to know there was an open source version. However I observe that the website's response and my response when I self-host using the exact same stack listed in `.env_example` are very different. The responses on the website are usually much better in quality than the ones I self-host.

It's totally fine if the website's version is made better than the open source's one for business purpose. I am just wondering whether you can disclose what the differences are. Thanks

**Comment by YassKhazzan** [comment]
Thanks for the support. the website version uses the OpenPerplex API so it's not exactly the same techniques but it still the same technical stack. maybe i'm going to opensource the API version in the future
