### ISSUE TITLE
OpenAI-compativle External Function Calling

### ISSUE THREAD

**Issue by kidehen** [YassKhazzan/openperplex_backend_os#3]
An external function integration hook, compatible with the [OpenAI approach](
https://platform.openai.com/docs/guides/function-calling), that makes Retrieval Augmented Generation (RAG) possible.

**Comment by YassKhazzan** [comment]
An API will be launched in the near future that will integrate RAG (Retrieval-Augmented Generation) functionality. This API will provide the capability to add various document types such as PDF, Word, and plain text files, as well as website content, to your RAG-enabled space.
