### ISSUE TITLE
OpenAPI-compliant API Description Documents for Service API

### ISSUE THREAD

**Issue by kidehen** [YassKhazzan/openperplex_backend_os#4]
I note you have released an API, but it doesn't currently include OpenAPI-compliant YAML or JSON documents that describe service endpoints and call patterns for REST-ful interaction.

**Comment by YassKhazzan** [comment]
will do that soon, but you can start using the alpha version for testing!!

**Comment by YassKhazzan** [comment]
Done : docs.openperplex.com
